// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameRefreshToken = "refresh_tokens"

// RefreshToken mapped from table <refresh_tokens>
type RefreshToken struct {
	ID          string    `gorm:"column:id;primaryKey;default:gen_random_uuid()" json:"id"`
	UserID      string    `gorm:"column:user_id;not null" json:"user_id"`
	HashedToken string    `gorm:"column:hashed_token;not null" json:"hashed_token"`
	IPAddress   string    `gorm:"column:ip_address;not null" json:"ip_address"`
	Used        bool      `gorm:"column:used" json:"used"`
	CreatedAt   time.Time `gorm:"column:created_at;default:now()" json:"created_at"`
}

// TableName RefreshToken's table name
func (*RefreshToken) TableName() string {
	return TableNameRefreshToken
}
