version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: postgres-local-test-task
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  minio_data:

networks:
  backend-network:
